### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by shiffman** [ml5js/Code-of-Conduct#11]
As discussed in #5, an FAQ would be helpful to answer common questions and clarify "legalese" or other technical language in the license / code of conduct. I am also quoting @joeyklee's [question](https://github.com/ml5js/Code-of-Conduct/pull/5#pullrequestreview-563950063) which is relevant for this FAQ discussion. 

> This is a non-blocking / clarifying question
> 
> > Each contributor licenses you to do everything with this software that would otherwise infringe that contributor’s copyright in it.
> 
> * I understand this to mean that: "Every person that contributes to this software agrees that  anyone else can change the software -- build on top of, edit, update, etc -- as long as it does not break the agreement specified in this copyright"
> 
> Am I understanding that correctly? So in other words, "it's all good except that you can't break the rules here" ...?

**Comment by mwweinberg** [comment]
Yes to the FAQ.  And yes to @joeyklee's question.  That understanding is the intent of the license language.  We are trying to remove all barriers to reuse/improvement/modification except those that we are explicitly calling out (essentially comply with the CoC, include a copy of the license in your version).

**Comment by mwweinberg** [comment]
We've started the FAQ [here](https://github.com/ml5js/Code-of-Conduct/blob/main/FAQ.md).  It is far from complete, but hopefully it is a place where we can at least start collecting the Qs.
