### ISSUE TITLE
Canonical URL for the license

### ISSUE THREAD

**Issue by shiffman** [ml5js/Code-of-Conduct#6]
We need something for:

> You must ensure that everyone who gets a copy of any part of this software from you, with or without changes, also gets the text of this license or a link to [canonical URL for the license].

Should it be this repo or should we set up a permanent forwarding URL like https://ml5js.org/license?

**Comment by mwweinberg** [comment]
I don't think there is an intrinsically right answer to this question.  Is one of them either easier to maintain or format?

**Comment by shiffman** [comment]
I like the idea of the ml5 domain since it points people to the main website as well as allows us to easily swap out something new if we change the GitHub organization and/or move to another platform. @bomanimc would a redirect to https://github.com/ml5js/Code-of-Conduct/blob/main/LICENSE.md be simple to add? This is low priority and shoudn't be a roadblock to moving forward, we can just use the github URL in the meantime.

**Comment by bomanimc** [comment]
@shiffman Yeah I think that would be quite simple to add via Netlify. I'll give it a shot now.
